### ISSUE TITLE
Dumping the data by user-define walltime

### ISSUE THREAD

**Issue by Anchewei** [gamer-project/gamer#156]
As the time-steps of the simulation get smaller, the users need to wait more time to get the next snapshot, so it is possible that it may waste the resource if we can’t get the snapshot before it is terminated.

Is it possible to add a parameter to specify the dumping time by walltime?

**Comment by hfhsieh** [comment]
@Anchewei You can find the unofficial, tentative version in the `master_dump_walltime` branch [here](https://github.com/hfhsieh/gamer-fork/tree/master_dump_walltime). All modifications are inlcuded in this [commit](https://github.com/hfhsieh/gamer-fork/commit/916e5520f820fd1c6fde262e818a882b6a840412)

You can use `cherry-pick` to merge that commit. To use it, you must enable `TIMING` and set the runtime parameter `OUTPUT_WALLTIME` to a non-negative number (in second).

**Comment by hyschive** [comment]
@hfhsieh Thanks for the quick response! I have several comments if you would like to submit a PR for this new feature.
- [ ] Instead of relying on `Timer_Main`, I would suggest adding a new timer `Timer_OutputWalltime`, which can be declared and initiated [here](https://github.com/gamer-project/gamer/blob/master/src/Main/Main.cpp#L486-L487).
  - [ ] It will make this feature independent of other timers (e.g., in case we change `Timer_Main` someday).
  - [ ] It will work even without `TIMING`.
- [ ] For checking when to output data, how about doing that [here](https://github.com/gamer-project/gamer/blob/master/src/Output/Output_DumpData.cpp#L173) in `Output_DumpData()` instead of in `Main()`? It will be more consistent with other output criteria.
  - [ ] You can mimic `OutputData_RunTime`.
  - [ ] Use `Timer_OutputWalltime.Stop()/GetValue()/Reset()`.
  - [ ] Then we don't need `OUTPUT_ELAPTIME`.
- [ ] Would it be possible to use the `day/hour/min/sec` format for `OUTPUT_WALLTIME`?
- [ ] Record `OUTPUT_WALLTIME` in `Aux_TakeNote()`.

**Comment by hfhsieh** [comment]
@hyschive My concern is that do we need this feature in GAMER. If yes, I can implement this feature formally.

**Comment by hyschive** [comment]
@hfhsieh I think so. This feature is particularly useful when running large simulations on a large supercomputer (e.g., NCHC) and has been commonly implemented in other codes (e.g., see the `CpuTimeBetRestartFile` option in [Gadget-4](https://wwwmpa.mpa-garching.mpg.de/gadget4/gadget4_manual.pdf)).

**Comment by hyschive** [comment]
@hfhsieh BTW, it's ok to use only _seconds_ in `OUTPUT_WALLTIME`. You make the call.

**Comment by Anchewei** [comment]
@hfhsieh Sorry for the late reply, I just find that the notification was detected as spam in my Gmail.
Also, thank you for the modifications, I will check that in recent days and let you know if there is any problem.

**Comment by hyschive** [comment]
@Anchewei #157

**Comment by hyschive** [comment]
Implemented in #157.
