### ISSUE TITLE
Some issues of the Hydro test problems

### ISSUE THREAD

**Issue by JeiwHuang** [gamer-project/gamer#161]
1. Aboout **TestProb_Hydro_JeansInstability** , 
`FLOAT8` should be required to be enabled in `example/test_problem/Hydro/JeansInstability/README` and `src/TestProblem/Hydro/JeansInstability/Init_TestProb_Hydro_JeansInstability.cpp`.

2. About  **TestProb_Hydro_Bondi**, 
the plotting scripts (`plot_diagonal.gpt`, `plot_profile.gpt`)  in `example/test_problem/Hydro/Bondi/` are not working well.

3. About **TestProb_Hydro_Gravity**,
it got the following error while running (maybe it is too old):
```
ERROR : Interpolate_Iterate() failed !!
NComp=5, IntScheme=4, UnwrapPhase=0, Monotonic=1, OppSign0thOrder=1
FData_is_Prim=1, Iter=11, IntMonoCoeff=0.0000000e+00
Fluid:  [0]= 2.7629648e-07 [1]= 6.3926416e+03 [2]= 4.4633426e+04 [3]=           inf [4]=          -nan
```

4. The `plot.gpt` in the [Wiki: Quick Start: 1D Shock Tube](https://github.com/gamer-project/gamer/wiki/Quick-Start%3A-1D-Shock-Tube) now has a different name as `plot__hydro_dens.gpt` (in `example/test_problem/Hydro/Riemann`).

**Comment by hyschive** [comment]
@JeiwHuang 
- For `TestProb_Hydro_Bondi`, it is recommended to enable `DUAL_ENERGY`. Then `plot_diagonal.gpt` can work. Besides, `plot_profile.gpt` is for analyzing the profile data generated by `gamer_extract_profile`. So both of them are not real bugs.
- Other issues have been fixed by #163. The `Quick Start` page on wiki has also been updated.
