### ISSUE TITLE
Supporting Volta arch

### ISSUE THREAD

**Issue by jzuhone** [gamer-project/gamer#4]
This issue is just a placeholder for discussion about what will be necessary for supporting the Volta GPU architecture.

**Comment by hyschive** [comment]
Supporting Volta GPU should be quite straightforward. The minimum required modifications can be found by `grep -r PASCAL`:

1. Add `#define VOLTA       5` to `include/Macro.h`
2. Modify `include/CUFLU.h`, `include/CUPOT.h`, `src/Auxiliary/Aux_TakeNote.cpp`, `src/GPU_API/CUAPI_SetDevice.cu`, and `src/GPU_API/CUAPI_Set_Default_GPU_Parameter.cu` to include `VOLTA` by simply following the setup of `PASCAL`
3. Add the following lines to the `Makefile`
`else ifeq "$(filter -DGPU_ARCH=VOLTA,  $(SIMU_OPTION))" "-DGPU_ARCH=VOLTA"`
`   NVCCFLAG_COM += -gencode arch=compute_70,code=\"compute_70,sm_70\"`

In principle, that's all we need to do. But I do not have access to any VOLTA GPU currently to actually test it. Also, it may be possible to use a larger PATCH_SIZE on Volta due to the larger shared memory size.

**Comment by hyschive** [comment]
That's great! If it's not super urgent, I can help implement it early next week (just to make it compilable with `GPU_ARCH=VOLTA`) so that your colleague could help test it.

**Comment by hyschive** [comment]
I just found that Volta requires CUDA >= 9.0, which deprecates the shuffle functions used by CUDA < 9.0. See this [link](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#warp-shuffle-functions). I'm looking into this issue and will try to add support for `GPU_ARCH=VOLTA` in the next few days.

**Comment by hyschive** [comment]
The commit 97b48ee adds support for Volta. So I'll close this issue. Note however that the performance on Volta may be optimized further.
